### PR TITLE
Performance issues, dependency bumps and solved todo's

### LINKED ISSUE #330: Fix performance issues in monaco-validation-library
When using a starter character like ```<``` in combination with a parent element with a lot of child options in the xsd the monaco editor and sometimes even the browser crashes completely.

### PR DESCRIPTION
**Pull request by stijnpotters1**
Before the library had +/- 89 vulnerabilities so i have bumped a lot of dependencies and changed code. Now there are 0 vulnerabilities left.

This todo was open:
**Replace element ref namespace with namespace used in the XML.**

Before it was ref="tns:Pipe" and with namespace "fr" → "fr:tns:Pipe"                  This broke the xml.
After the changes ref="tns:Pipe" → strip "tns:" apply namespace → "fr:Pipe"      This works correct.

**Performance optimisations**
Previously XPath was used for search queries, but the search queries were searching through the whole xsd which resulted in an O(N) notation throughout all different kind of searches. I removed XPath and implemented map indexing with help of the xmldom library. I transformed the code so it has an O(N) notation at the beginning while indexing. after this the searches will be O(1), O(K)  and O(A) for different kind fo searches.

N:  amount of nodes (elements)
K:  Relevant nodes in this subtree
A:  Amount of attributes of an element.

@philipsens You can build this new version of the library and link it to the new flow that uses the new FrankConfig.xsd
So you can test this properly first

```
cd C:\.........\flow\src\main\frontend
pnpm link C:\......
```

### CODE REVIEW

File: src/CodeSuggester.ts [hunk 1]
```diff
@@ -51,12 +50,19 @@ export default class CodeSuggester {
...
-                }
-            },
-        )
+                },
+            ]
+        })
 
-    private parseElementName = (name: string, namespace: string | undefined) =>
-        namespace ? namespace + ':' + name : name
+    private stripNsPrefix = (name: string): string => {
```
Comment (philipsens) [inline src/CodeSuggester.ts]: This method is also used in XsdParser.ts. Maybe you could move both methods to the SimpleParser.ts to minimize duplication.

File: src/XsdNamespaces.ts [hunk 2]
```diff
@@ -6,8 +6,32 @@ import { SimpleParser } from './SimpleParser'
...
+        if (typeof model !== 'string') {
+            const key = `${model.uri.toString()}:${model.getVersionId()}`
+            if (key === XsdNamespaces.cacheKey && XsdNamespaces.cachedResult) {
+                return XsdNamespaces.cachedResult
+            }
+
+            const text = model.getValueInRange({
+                startLineNumber: 1,
+                startColumn: 1,
+                endLineNumber: 50,
```
Comment (philipsens) [inline src/XsdNamespaces.ts]: Why only 50 lines and not `getFullModelRange()` like it used to be?

File: src/XsdParser.ts [hunk 3]
```diff
@@ -1,243 +1,327 @@
...
+const CONTAINER_NODES = new Set(['sequence', 'all', 'complexContent', 'extension', 'restriction'])
+
 export default class XsdParser {
     private readonly xsd: IXsd
-    private readonly namespace: string
-    private readonly xsdDom: Document
-    private readonly select: xpath.XPathSelect
+    private readonly xsdDoc: Document
+
+    // these indexes are built once at construction time for fast lookups during code completions
```
Comment (philipsens) [inline src/XsdParser.ts]:
```suggestion
    // These indexes are built once at construction time for fast lookups during code completions
```

File: src/XsdParser.ts [hunk 4]
```diff
@@ -1,243 +1,327 @@
...
 
-        const sequences = this.getSequencesInNode(complexType)
+    /**
+     * Reads the base type from an xs:element with an inline complexType that extends another type:
+     */
+    private readExtensionBase(element: Element): string | null {
+        const ct = this.firstChildElement(element, 'complexType')
+        const cc = ct && this.firstChildElement(ct, 'complexContent')
+        const ext = cc && this.firstChildElement(cc, 'extension')
+        return ext ? ext.getAttribute('base') : null
```
Comment (philipsens) [inline src/XsdParser.ts]: I don't really like the acronyms because that the first thing that I'm reading. I have to look ahead kind of before continuing to read where I left. I know it is small, but it can improve reading the code and doing the review.

File: src/XsdParser.ts [hunk 5]
```diff
@@ -1,243 +1,327 @@
...
+            } else if (localName === 'choice') {
+                firstOnly
+                    ? this.collectFirstChoice(child, result, visited)
+                    : this.collectElements(child, result, visited, false)
+            } else if (CONTAINER_NODES.has(localName)) {
+                this.collectElements(child, result, visited, firstOnly)
+            } else if (localName === 'group') {
+                this.followGroupRef(child, result, visited, firstOnly)
+            }
         }
```
Comment (philipsens) [inline src/XsdParser.ts:162]: This would be nicer to read because of the destruct and the switch case stating clear cases.

```suggestion
        for (const child of this.elementChildren(node)) {
		    const { localName } = child
		    switch (localName) {
		        case 'element':
		            result.push(child)
		            break
		        case 'choice':
		            firstOnly
		                ? this.collectFirstChoice(child, result, visited)
		                : this.collectElements(child, result, visited, false)
		            break
		        case 'group':
		            this.followGroupRef(child, result, visited, firstOnly)
		            break
		        default:
		            if (CONTAINER_NODES.has(localName)) {
		                this.collectElements(child, result, visited, firstOnly)
		            }
		            break
		    }
		}
```

Was the order of `if (CONTAINER_NODES.has(localName))` important being second to last?

File: src/XsdParser.ts [hunk 6]
```diff
@@ -1,243 +1,327 @@
...
+        for (const child of this.elementChildren(node)) {
+            const localName = child.localName
+            if (localName === 'attribute') {
+                result.push(child)
+            } else if (['complexContent', 'extension', 'restriction'].includes(localName)) {
+                result.push(...this.collectAttributes(child))
+            } else if (localName === 'attributeGroup') {
+                const ref = child.getAttribute('ref')
+                if (ref) result.push(...this.attributesFromGroup(this.stripNsPrefix(ref)))
+            }
```
Comment (philipsens) [inline src/XsdParser.ts]: Although this has fewer cases, I'd still prefer a switch so it is easier to spot the pattern.

File: src/CodeSuggester.ts [hunk 7]
```diff
@@ -51,12 +50,19 @@ export default class CodeSuggester {
...
+        const idx = name.indexOf(':')
+        return idx !== -1 ? name.substring(idx + 1) : name
```
Comment (philipsens) [inline src/CodeSuggester.ts]: https://abbrify.com/abbreviation-and-acronym/IDX? 👀

**Review by philipsens — COMMENTED** [review]
Thanks for your contribution I appreciate the level of optimization.

There are a few comments about abbreviations and readability.

File: src/CodeSuggester.ts (hunk 7 above)
Comment (stijnpotters1) [reply src/CodeSuggester.ts]: ah i see, i have made it more clear and readable!

**Review by philipsens — APPROVED** [review]
Thanks again!
